# Exported from Render on 2025-07-31T04:46:57Z
services:
- type: web
  name: AcdaLink
  runtime: python
  repo: https://github.com/GNANASEELAN05/AcdaLink
  plan: free
  region: singapore
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
  autoDeployTrigger: commit
version: "1"
